Repository Cafe-Manage-Service-CAFE-IN/cafe-in, pull requests merged in 2023-08, with the labels that each got.

#33 [#30][FEATURE] 관리자 - 카테고리 추가, 수정, 삭제 기능 수정
  src/components/MenuManagement/CategoryItem.tsx
  src/components/MenuManagement/CategoryList.tsx
  src/components/MenuManagement/CategoryManagementModal.tsx
  src/components/MenuManagement/Header.tsx
  src/components/MenuManagement/MenuList.tsx
  src/pages/admin/MenuManagement.tsx
  src/state/MenuListState.ts
Labels: ✨ Feature

#35 [#26][✨FEATURE] 사용자 - 대기 신청 기능 구현
  public/assets/user/minusicon_able_light.svg
  src/components/waitingManagement/WaitingHeader.tsx
  src/components/waitingManagement/WaitingItem.tsx
  src/pages/admin/WaitingManagement.tsx
  src/pages/user/MenuList.tsx
  src/pages/user/Waiting.tsx
  src/pages/user/WaitingCheck.tsx
  src/state/WaitingState.ts
Labels: 🐛 BugFix, ✨ Feature

#44 [#42][FEATURE] 관리자 - 로그인 페이지
  public/assets/logo_dark.png
  src/pages/admin/AdminLogin.tsx
Labels: ✨ Feature, 🎨 Style

#48 [#47][FEATURE] 관리자 - 주문 내역 확인 페이지
  src/App.tsx
  src/components/OrderHistory/Header.tsx
  src/components/OrderHistory/OrderItem.tsx
  src/components/OrderHistory/OrderList.tsx
  src/components/OrderHistory/OrderListContainer.tsx
  src/pages/admin/OrderHistory.tsx
Labels: 🎨 Style

#50 [#43][✨FEATURE] 관리자 - 테마 및 색상 설정 기능 구현
  public/assets/admin/blueColor.svg
  public/assets/admin/greenColor.svg
  public/assets/admin/moon-selected_dark.svg
  public/assets/admin/moon_dark.svg
  public/assets/admin/moon_light.svg
  public/assets/admin/pinkColor.svg
  public/assets/admin/purpleColor.svg
  public/assets/admin/sun-selected_light.svg
  public/assets/admin/sun_dark.svg
  public/assets/admin/sun_light.svg
  public/assets/admin/yellowColor.svg
  src/App.tsx
  src/components/adminMode/ManagementHeader.tsx
  src/components/customSVG/RenderMinusIcon.tsx
  src/components/customSVG/RenderPlusIcon.tsx
  src/components/customSVG/WaitingSVG.tsx
  src/components/waitingManagement/WaitingApplyModal.tsx
  src/components/waitingManagement/WaitingItem.tsx
  src/components/waitingManagement/WaitingModal.tsx
  src/components/waitingManagement/WaitingTableBox.tsx
  src/hooks/useSelectedColor.ts
  src/pages/admin/AdminMenu.tsx
  src/pages/admin/ThemeManagement.tsx
  src/pages/admin/WaitingManagement.tsx
  src/pages/user/Waiting.tsx
  src/pages/user/WaitingCheck.tsx
  src/state/ColorState.ts
  src/style/theme.ts
  src/types/styled.d.ts
Labels: ✨ Feature, 🎨 Style

#54 [#49][FEATURE] 관리자 - 주문 내역 확인 페이지 기능 구현
  src/components/OrderHistory/Header.tsx
  src/components/OrderHistory/OrderItem.tsx
  src/components/OrderHistory/OrderList.tsx
  src/components/OrderHistory/OrderListContainer.tsx
  src/pages/admin/OrderHistory.tsx
  src/types/orderHistoryType.ts
  src/utils/changeDateFormat.ts
Labels: ✨ Feature

#58 [#55][FEATURE] 관리자 - 메뉴 관리 페이지 기능 수정
  src/components/MenuItem.tsx
  src/components/MenuManagement/CategoryManagementModal.tsx
  src/components/MenuManagement/Header.tsx
  src/components/MenuManagement/ModalInput.tsx
  src/components/OrderHistory/Header.tsx
  src/components/adminMode/HeaderButton.tsx
  src/components/adminMode/ManagementHeader.tsx
  src/pages/admin/MenuManagement.tsx
Labels: ⛏ Refactor, ✨ Feature

#60 [#59][FEATURE] 관리자 - 메뉴 관리 / 주문 내역 확인 페이지 테마 적용 반영 스타일 수정
  src/App.tsx
  src/components/MenuManagement/AddMenuModal.tsx
  src/components/MenuManagement/CategoryItem.tsx
  src/components/MenuManagement/CategoryList.tsx
  src/components/MenuManagement/CategoryManagementModal.tsx
  src/components/MenuManagement/DeleteModal.tsx
  src/components/MenuManagement/EditMenuModal.tsx
  src/components/MenuManagement/Header.tsx
  src/components/MenuManagement/ModalInput.tsx
  src/components/OrderHistory/OrderList.tsx
  src/components/adminMode/HeaderButton.tsx
  src/index.tsx
  src/pages/admin/AdminLogin.tsx
  src/pages/admin/MenuManagement.tsx
  src/types/styled.d.ts
Labels: ✨ Feature, 🎨 Style

#62 [#61][FEATURE] 관리자 - 주문 내역 확인 데이터 관련 코드 수정
  src/components/OrderHistory/OrderList.tsx
  src/components/OrderHistory/OrderListContainer.tsx
  src/types/orderHistoryType.ts
Labels: ✨ Feature

#63 [#52][✨FEATURE] 사용자 - 포인트 적립 & 포인트 사용
  src/components/UserMode/AddPointModal.tsx
  src/components/UserMode/CheckPointUsedIt.tsx
  src/components/UserMode/PointAddCheckModal.tsx
  src/components/UserMode/UsePointUser.tsx
  src/pages/user/OrderCheck.tsx
  src/state/PointState.ts
Labels: ✨ Feature

#66 Feature/[#64][✨FEATURE] 관리자- 포인트 내역조회
  src/components/UserMode/MenuListHeader.tsx
  src/components/UserMode/OptionMenu.tsx
  src/components/UserMode/SelectedItemContainer.tsx
  src/components/adminMode/HeaderButton.tsx
  src/components/adminMode/ManagementHeader.tsx
  src/components/darkThemeModal/Dark_PointAddCheckModal.tsx
  src/pages/Home.tsx
  src/pages/admin/PointList.tsx
  src/pages/user/MenuList.tsx
  src/pages/user/OrderCheck.tsx
Labels: ✨ Feature

#68 [#57][✨FEATURE] 썸네일 및 나머지 페이지 마크업 및 스타일링
  public/apple-icon-72x72.png
  public/assets/admin/sorryIcon.svg
  public/assets/admin/sorryIcon_dark.svg
  public/assets/logo_beige.svg
  public/assets/logo_beige_small.svg
  public/assets/logo_dark_small.svg
  public/assets/paw_adminIcon.svg
  public/favicon.ico
  public/index.html
  src/App.tsx
  src/components/waitingManagement/WaitingItem.tsx
  src/components/waitingManagement/WaitingTableBox.tsx
  src/pages/Home.tsx
  src/pages/NotFound.tsx
  src/pages/Thumbnail.tsx
  src/pages/admin/AdminMenu.tsx
  src/pages/user/Start.tsx
  src/pages/user/Waiting.tsx
  src/style/theme.ts
  src/types/styled.d.ts
Labels: 🥰 Accessibility, 🎨 Style

#67 [#65][REFACTOR] 관리자 - 메뉴 관리 페이지 로그인 관련 리코일 코드 수정
  src/components/MenuItem.tsx
  src/state/Mode.ts
Labels: ⛏ Refactor

#70 [#69][🔨 REFACTOR] 페이지 색상 적용 코드 수정 및 페이지 연결하기
  public/assets/logo_small.svg
  src/App.tsx
  src/components/customSVG/RenderPlusIcon.tsx
  src/components/customSVG/WaitingSVG.tsx
  src/components/waitingManagement/WaitingApplyModal.tsx
  src/components/waitingManagement/WaitingItem.tsx
  src/components/waitingManagement/WaitingModal.tsx
  src/components/waitingManagement/WaitingTableBox.tsx
  src/pages/Thumbnail.tsx
  src/pages/admin/AdminLogin.tsx
  src/pages/admin/AdminMenu.tsx
  src/pages/admin/ThemeManagement.tsx
  src/pages/admin/WaitingManagement.tsx
  src/pages/user/Start.tsx
  src/pages/user/Waiting.tsx
  src/pages/user/WaitingCheck.tsx
Labels: ⛏ Refactor, 🎨 Style

#71 [🔨 refactor] 결제하기 데이터 삭제 취소
  src/pages/user/OrderCheck.tsx
Labels: ✨ Feature

#73 [#72][REFACTOR] 관리자 - 로그인 / 메뉴 관리 / 주문 내역 확인 페이지 색상 수정
  src/components/MenuManagement/CategoryItem.tsx
  src/components/MenuManagement/CategoryManagementModal.tsx
  src/components/OrderHistory/OrderList.tsx
  src/pages/admin/AdminLogin.tsx
Labels: ⛏ Refactor, 🥰 Accessibility

#77 [#74][FEATURE] 관리자 - 관리자 페이지 로그인 여부로 접근 제한 기능 추가
  src/components/adminMode/WithAuth.tsx
  src/pages/Thumbnail.tsx
  src/pages/admin/AdminMenu.tsx
  src/pages/admin/MenuManagement.tsx
  src/pages/admin/OrderHistory.tsx
  src/pages/admin/PointList.tsx
  src/pages/admin/SalesList.tsx
  src/pages/admin/ThemeManagement.tsx
  src/pages/admin/WaitingManagement.tsx
Labels: ✨ Feature

#79 [#78][REFACTOR] 관리자 - 주문 내역 확인 페이지 버튼 렌더링 수정
  src/components/OrderHistory/OrderList.tsx
  src/components/OrderHistory/OrderListContainer.tsx
Labels: ⛏ Refactor

#76 [#64][✨FEATURE] orderList progress 상태 따라 렌더링
  src/components/UserMode/MenuItem.tsx
  src/components/UserMode/SelectedItemContainer.tsx
  src/pages/user/OrderCheck.tsx
Labels: ✨ Feature

#81 [#80][FEATURE] 관리자 - 로그인 리다이렉트 안내 토스트 메세지
  src/components/adminMode/Toast.tsx
  src/components/adminMode/WithAuth.tsx
  src/pages/Thumbnail.tsx
  src/pages/admin/AdminLogin.tsx
  src/pages/admin/MenuManagement.tsx
  src/pages/admin/OrderHistory.tsx
Labels: ✨ Feature, 🎨 Style

#83 [#82][🔨 REFACTOR] 시작 페이지 홈으로 이동하기 추가 및 스타일링 수정
  src/pages/user/Start.tsx
Labels: ✨ Feature, 🎨 Style

#84 [#75][✨FEATURE] 매출 내역 조회 페이지 마크업 및 스타일링, 기능 구현
  src/pages/admin/SalesList.tsx
Labels: 🥰 Accessibility, ✨ Feature, 🎨 Style

#86 [#85][REFACTOR] 데이터 키 값 수정, 함수 분리
  src/components/MenuItem.tsx
  src/components/OrderHistory/OrderList.tsx
  src/components/OrderHistory/OrderListContainer.tsx
  src/types/orderHistoryType.ts
  src/utils/changeFormat.ts
Labels: ⛏ Refactor

#90 [#89][REFACTOR] Toast 컴포넌트 재사용 가능하게 수정
  src/components/adminMode/Toast.tsx
  src/pages/Thumbnail.tsx
Labels: ⛏ Refactor

#92 [#88][✨FEATURE] 관리자 - 포인트 내역 조회 페이지 수정
  src/pages/admin/PointList.tsx
Labels: ⛏ Refactor, 🎨 Style

#93 [#64][REFACTOR] 로컬상태 변경
  src/components/UserMode/MenuItem.tsx
  src/components/UserMode/MenuListHeader.tsx
  src/components/UserMode/OptionMenu.tsx
  src/components/UserMode/SelectedItemContainer.tsx
  src/firebase/FirStoreDoc.ts
  src/pages/user/OrderCheck.tsx
  src/state/OrderListAtom.ts
  src/types/Category.ts
  src/types/OptinalState.ts
  src/types/Order.ts
Labels: ⛏ Refactor

#94 [#87][🔨 REFACTOR] 매출 관리 - 유틸 함수 사용 및 데이터 변경
  src/pages/admin/SalesList.tsx
Labels: ⛏ Refactor

#96 [#95][REFACTOR] 메뉴 관리, 주문 내역 확인 페이지 스크롤 수정
  src/components/MenuManagement/CategoryManagementModal.tsx
  src/components/OrderHistory/OrderItem.tsx
  src/components/OrderHistory/OrderList.tsx
  src/pages/admin/MenuManagement.tsx
  src/pages/admin/OrderHistory.tsx
Labels: ⛏ Refactor

#99 [#97][FEATURE] 모든 모달 배경 클릭시 닫는 기능 추가
  src/components/MenuManagement/AddMenuModal.tsx
  src/components/MenuManagement/CategoryManagementModal.tsx
  src/components/MenuManagement/DeleteModal.tsx
  src/components/MenuManagement/EditMenuModal.tsx
Labels: ✨ Feature

#100 [#91][✨ FEATURE & 🔨 REFACTOR]사용자- 메뉴리스트 , 주문확인 내역, 선택아이템 수정
  src/components/UserMode/AddPointModal.tsx
  src/components/UserMode/CheckPointUsedIt.tsx
  src/components/UserMode/MenuItem.tsx
  src/components/UserMode/MenuListHeader.tsx
  src/components/UserMode/OptionMenu.tsx
  src/components/UserMode/PointAddCheckModal.tsx
  src/components/UserMode/SelectedItemContainer.tsx
  src/components/UserMode/UsePointUser.tsx
  src/components/adminMode/Toast.tsx
  src/components/darkThemeModal/Dark_PointAddCheckModal.tsx
  src/pages/user/MenuList.tsx
  src/pages/user/OrderCheck.tsx
  src/pages/user/Start.tsx
  src/state/TakeOut.ts
  src/types/Order.ts
Labels: ⛏ Refactor, ✨ Feature

#101 [🎨 style] 색상코드 수정2
  src/components/UserMode/AddPointModal.tsx
  src/components/UserMode/CheckPointUsedIt.tsx
  src/components/UserMode/MenuListHeader.tsx
  src/components/UserMode/OptionMenu.tsx
  src/components/UserMode/PointAddCheckModal.tsx
  src/components/UserMode/SelectedItemContainer.tsx
  src/components/UserMode/UsePointUser.tsx
  src/pages/user/OrderCheck.tsx
Labels: ⛏ Refactor

#104 [#103]/ [🔨 REFACTOR] 스타일 등등 수정
  src/components/UserMode/AddPointModal.tsx
  src/components/UserMode/CheckPointUsedIt.tsx
  src/components/UserMode/MenuItem.tsx
  src/components/UserMode/UsePointUser.tsx
  src/components/adminMode/Toast.tsx
  src/pages/user/MenuList.tsx
  src/pages/user/OrderCheck.tsx
Labels: ⛏ Refactor

#107 [#106][ 🔨 REFACTOR] 웹 접근성 성능개선
  src/components/UserMode/MenuListHeader.tsx
  src/components/UserMode/SelectedItemContainer.tsx
  src/pages/user/OrderCheck.tsx
  src/style/theme.ts
Labels: ⛏ Refactor, 🥰 Accessibility

#111 [#110][ 🔨 REFACTOR] 다크 모드 적용 안된 부분 수정 및 불필요한 코드 수정
  src/hooks/useSelectedColor.ts
  src/pages/Thumbnail.tsx
  src/pages/admin/AdminMenu.tsx
  src/pages/admin/PointList.tsx
  src/pages/user/Start.tsx
Labels: 🎨 Style

#113 [#105][REFACTOR] 웹 접근성 및 성능 개선
  src/components/MenuItem.tsx
  src/components/MenuManagement/AddMenuModal.tsx
  src/components/MenuManagement/CategoryItem.tsx
  src/components/MenuManagement/CategoryList.tsx
  src/components/MenuManagement/CategoryManagementModal.tsx
  src/components/MenuManagement/DeleteModal.tsx
  src/components/MenuManagement/EditMenuModal.tsx
  src/components/MenuManagement/ModalInput.tsx
  src/components/OrderHistory/OrderItem.tsx
  src/components/OrderHistory/OrderList.tsx
  src/components/adminMode/HeaderButton.tsx
  src/pages/admin/AdminLogin.tsx
  src/pages/admin/MenuManagement.tsx
  src/pages/admin/OrderHistory.tsx
  src/style/global.ts
  src/style/theme.ts
Labels: ⛏ Refactor

#114 [#112][🔨 REFACTOR] 메뉴 리스트, 포인트 , 다크모드 수정
  src/components/UserMode/CheckPointUsedIt.tsx
  src/components/UserMode/SelectedItemContainer.tsx
  src/pages/user/OrderCheck.tsx
Labels: ⛏ Refactor

#115 [🔨 REFACTOR] Open Graph 설정 및 Eslint 경고 코드 수정
  public/cafein_thumbnail.png
  public/index.html
  src/components/UserMode/SelectedItemContainer.tsx
Labels: ⛏ Refactor

#116 [🔧 setting ] robots.txt 추가
  public/robots.txt
Labels: 🌎 Deploy

#119 [#118][🔨 REFACTOR] 대기 신청 페이지 유효성 검사 추가 및 매일 대기 번호 초기화
  src/pages/user/Waiting.tsx
  src/pages/user/WaitingCheck.tsx
Labels: ⛏ Refactor

#122 [#105][FEATURE] 메뉴 관리 페이지 수정
  src/components/MenuItem.tsx
  src/components/MenuManagement/ModalInput.tsx
  src/pages/admin/MenuManagement.tsx
Labels: ⛏ Refactor

#120 [#118][🔨 REFACTOR] 매일 대기 번호 초기화 코드 수정
  src/pages/user/Waiting.tsx
Labels: ⛏ Refactor

#123 [#121][🔨 REFACTOR] 매출 관리 - 해당 날짜 데이터만 가져오는 코드 수정
  src/pages/admin/SalesList.tsx
  src/utils/changeFormat.ts
Labels: 🐛 BugFix, ⛏ Refactor

#124 [#118][🔨 REFACTORING] 카테고리, 메뉴리스트 등 수정
  src/components/UserMode/CheckPointUsedIt.tsx
  src/components/UserMode/MenuItem.tsx
  src/components/UserMode/MenuListHeader.tsx
  src/components/UserMode/SelectedItemContainer.tsx
  src/components/UserMode/UsePointUser.tsx
  src/pages/admin/PointList.tsx
  src/pages/user/OrderCheck.tsx
  src/state/PointState.ts
Labels: 🐛 BugFix, ⛏ Refactor, ✨ Feature

#127 [#125] 접근성 개선 및 다크모드 스타일 수정
  src/components/MenuManagement/CategoryItem.tsx
  src/components/MenuManagement/CategoryManagementModal.tsx
Labels: ⛏ Refactor

#129 [#128][🔨 REFACTORING] 메뉴 관리, 주문 관리 스타일 수정 및 eslint 경고 코드 수정
  src/components/MenuItem.tsx
  src/components/MenuManagement/CategoryItem.tsx
  src/components/MenuManagement/CategoryManagementModal.tsx
  src/components/MenuManagement/Header.tsx
  src/components/OrderHistory/Header.tsx
  src/components/OrderHistory/OrderItem.tsx
  src/components/adminMode/HeaderButton.tsx
  src/pages/admin/PointList.tsx
Labels: ⛏ Refactor, 🎨 Style

#131 [🔨 refactor] Category의 isShowOptionModal에 따라 모달 처리
  src/components/UserMode/MenuItem.tsx
  src/components/UserMode/MenuListHeader.tsx
  src/state/CategoryList.ts
  src/types/Category.ts
Labels: ⛏ Refactor, ✨ Feature
