Repository Cafe-Manage-Service-CAFE-IN/cafe-in, pull requests merged in 2023-07, with the labels that each got.

#6 [#2] [✨FEATURE] 관리자 - 대기 관리 페이지 마크업 및 스타일링
  src/components/waitingManagement/WaitingHeader.tsx
  src/components/waitingManagement/WaitingItem.tsx
  src/components/waitingManagement/WaitingModal.tsx
  src/pages/admin/WaitingManagement.tsx
  src/style/global.ts
  src/style/theme.ts
Labels: 🥰 Accessibility, 🎨 Style

#9 [#4] [✨FEATURE] 사용자 - 메뉴 조회 및 선택 마크업스타일링
  .eslintrc.json
  package-lock.json
  package.json
  public/assets/user/AllDeleteBtn.svg
  public/assets/user/IceCoffee.svg
  src/App.tsx
  src/components/MenuItem.tsx
  src/components/MenuListHeader.tsx
  src/components/OptionMenu.tsx
  src/components/SeletedItemContainer.tsx
  src/pages/user/MenuList.tsx
  src/state/OptinalState.ts
  src/style/global.ts
  tsconfig.json
Labels: 🎨 Style

#12 [#11][✨FEATURE] 파이어베이스 Firestore DB 연동
  .gitignore
  firebaseConfig.ts
  package-lock.json
  package.json
  src/components/waitingManagement/WaitingHeader.tsx
Labels: ✨ Feature

#16 [#14][✨FEATURE] 사용자 모드 / 관리자 모드 구분
  src/components/MenuItem.tsx
  src/pages/Home.tsx
  src/state/Mode.ts
Labels: ✨ Feature

#20 [#17][✨FEATURE] 관리자 - 카테고리 관리
  public/index.html
  src/components/MenuManagement/CategoryItem.tsx
  src/components/MenuManagement/CategoryList.tsx
  src/components/MenuManagement/CategoryManagementModal.tsx
  src/components/MenuManagement/Header.tsx
  src/components/ModalPortal.tsx
  src/pages/admin/MenuManagement.tsx
  src/state/CategoryList.ts
  src/state/Mode.ts
  src/types/categoryTypes.ts
Labels: ✨ Feature

#22 [#15] [✨FEATURE] 관리자- 대기 관리 기능 구현
  firebaseConfig.ts
  src/App.tsx
  src/components/waitingManagement/WaitingItem.tsx
  src/components/waitingManagement/WaitingModal.tsx
  src/components/waitingManagement/WaitingTableBox.tsx
  src/firebase/firebaseConfig.ts
  src/pages/admin/WaitingManagement.tsx
  src/state/modalState.ts
Labels: ✨ Feature

#25 [#23][🔨 refactor] 관리자 - 대기 관리 리팩토링 및 버그 수정
  src/App.tsx
  src/components/MenuItem.tsx
  src/components/waitingManagement/WaitingItem.tsx
  src/components/waitingManagement/WaitingModal.tsx
  src/components/waitingManagement/WaitingTableBox.tsx
  src/pages/admin/WaitingManagement.tsx
  src/state/Mode.ts
  src/types/waitingDataType.ts
  src/utils/filter.ts
Labels: 🐛 BugFix, ⛏ Refactor

#27 [🔨 refactor] 대기 관리 recoil 추가 및 머지 시 생겼던 오류 해결
  src/components/MenuItem.tsx
  src/components/MenuManagement/CategoryManagementModal.tsx
  src/components/waitingManagement/WaitingItem.tsx
  src/components/waitingManagement/WaitingModal.tsx
  src/pages/admin/WaitingManagement.tsx
  src/state/Mode.ts
  src/state/WaitingState.ts
Labels: 🐛 BugFix, ⛏ Refactor
